# Generated by Django 5.2 on 2025-04-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wificafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeblock',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
